import json
from sqlalchemy import select
from app.database import async_session
from app.models import Asset


ASSETS_SEED = [
    {"title": "Payment API Integration Guide", "description": "Step-by-step guide for integrating with the Payment API gateway", "tags": ["api", "payment", "integration", "guide"], "type": "PDF", "category": "Integration", "classification": "Internal", "kind": "Accelerator", "size": "2.4 MB", "uploaded_by": "Alice", "uploaded_at": "2026-07-08", "downloads": 145, "teams_url": "https://teams.microsoft.com/l/file/1", "status": "Published"},
    {"title": "Customer 360 PoC Report", "description": "Proof of concept results for Customer 360 data unification", "tags": ["poc", "customer360", "data", "integration"], "type": "Doc", "category": "CRM", "classification": "Internal", "kind": "PoC", "size": "4.1 MB", "uploaded_by": "Bob", "uploaded_at": "2026-07-07", "downloads": 89, "teams_url": "https://teams.microsoft.com/l/file/2", "status": "Review"},
    {"title": "Partner Portal Connectors", "description": "Repository of connectors for partner portal integration", "tags": ["connectors", "partner", "integration", "api"], "type": "Link", "category": "Integration", "classification": "External", "kind": "Repository", "size": "\u2014", "uploaded_by": "Charlie", "uploaded_at": "2026-07-06", "downloads": 234, "teams_url": None, "status": "Published"},
    {"title": "Healthcare API Demo", "description": "Client deliverable showcasing healthcare API interoperability", "tags": ["healthcare", "api", "demo", "deliverable"], "type": "Video", "category": "Healthcare", "classification": "External", "kind": "Client Deliverable", "size": "156 MB", "uploaded_by": "Diana", "uploaded_at": "2026-07-05", "downloads": 67, "teams_url": "https://teams.microsoft.com/l/file/4", "status": "Active"},
    {"title": "Integration Solutions Brochure", "description": "Marketing brochure highlighting key integration solutions", "tags": ["marketing", "brochure", "solutions", "integration"], "type": "PDF", "category": "Marketing", "classification": "External", "kind": "Marketing", "size": "5.7 MB", "uploaded_by": "Eve", "uploaded_at": "2026-07-04", "downloads": 312, "teams_url": None, "status": "Published"},
    {"title": "Annual Partner Summit", "description": "Event materials and recordings from the Annual Partner Summit", "tags": ["event", "partner", "summit", "annual"], "type": "Video", "category": "Events", "classification": "External", "kind": "Event", "size": "320 MB", "uploaded_by": "Frank", "uploaded_at": "2026-07-03", "downloads": 178, "teams_url": "https://teams.microsoft.com/l/file/6", "status": "Published"},
    {"title": "API Adoption Flyer", "description": "One-page flyer promoting API adoption best practices", "tags": ["flyer", "api", "adoption", "best-practices"], "type": "Image", "category": "Marketing", "classification": "Internal", "kind": "Flyer", "size": "0.8 MB", "uploaded_by": "Grace", "uploaded_at": "2026-07-02", "downloads": 423, "teams_url": None, "status": "Published"},
    {"title": "Integration Requirements Template", "description": "Reusable template for documenting integration requirements", "tags": ["template", "requirements", "documentation", "integration"], "type": "Doc", "category": "Process", "classification": "Internal", "kind": "Template", "size": "1.2 MB", "uploaded_by": "Alice", "uploaded_at": "2026-07-01", "downloads": 156, "teams_url": "https://teams.microsoft.com/l/file/8", "status": "Draft"},
    {"title": "REST API Design Workshop", "description": "Workshop materials for designing RESTful APIs", "tags": ["workshop", "rest", "api-design", "training"], "type": "PDF", "category": "Training", "classification": "Internal", "kind": "Workshop", "size": "8.3 MB", "uploaded_by": "Bob", "uploaded_at": "2026-06-30", "downloads": 287, "teams_url": "https://teams.microsoft.com/l/file/9", "status": "Published"},
    {"title": "Cloud Migration Playbook", "description": "Internal playbook for cloud migration integration patterns", "tags": ["cloud", "migration", "playbook", "internal"], "type": "PDF", "category": "Cloud", "classification": "Internal", "kind": "Accelerator", "size": "3.1 MB", "uploaded_by": "Charlie", "uploaded_at": "2026-06-29", "downloads": 91, "teams_url": "https://teams.microsoft.com/l/file/10", "status": "Active"},
    {"title": "Data Sync PoC Framework", "description": "Reusable framework for data synchronization proof of concepts", "tags": ["poc", "data-sync", "framework", "reusable"], "type": "Doc", "category": "Integration", "classification": "Internal", "kind": "PoC", "size": "2.8 MB", "uploaded_by": "Diana", "uploaded_at": "2026-06-28", "downloads": 143, "teams_url": None, "status": "Review"},
    {"title": "OpenAPI Spec Repository", "description": "Central repository for OpenAPI specifications across projects", "tags": ["openapi", "specification", "repository", "api"], "type": "Link", "category": "Integration", "classification": "External", "kind": "Repository", "size": "\u2014", "uploaded_by": "Eve", "uploaded_at": "2026-06-27", "downloads": 267, "teams_url": None, "status": "Published"},
    {"title": "Banking API Deliverable Pack", "description": "Client deliverable pack for banking API integration project", "tags": ["banking", "deliverable", "api", "client"], "type": "PDF", "category": "Finance", "classification": "External", "kind": "Client Deliverable", "size": "12.5 MB", "uploaded_by": "Frank", "uploaded_at": "2026-06-26", "downloads": 78, "teams_url": "https://teams.microsoft.com/l/file/13", "status": "Active"},
    {"title": "Integration Services Catalog", "description": "Marketing catalog of integration services and offerings", "tags": ["marketing", "catalog", "services", "integration"], "type": "PDF", "category": "Marketing", "classification": "External", "kind": "Marketing", "size": "6.2 MB", "uploaded_by": "Grace", "uploaded_at": "2026-06-25", "downloads": 198, "teams_url": None, "status": "Published"},
    {"title": "Tech Talks Webinar Series", "description": "Recorded webinars from the Tech Talks integration series", "tags": ["event", "webinar", "tech-talks", "recording"], "type": "Video", "category": "Events", "classification": "External", "kind": "Event", "size": "450 MB", "uploaded_by": "Alice", "uploaded_at": "2026-06-24", "downloads": 56, "teams_url": "https://teams.microsoft.com/l/file/15", "status": "Upcoming"},
    {"title": "Quick Start Flyer", "description": "Quick start guide flyer for new integration platform users", "tags": ["flyer", "quick-start", "guide", "new-users"], "type": "Image", "category": "Marketing", "classification": "Internal", "kind": "Flyer", "size": "0.5 MB", "uploaded_by": "Bob", "uploaded_at": "2026-06-23", "downloads": 345, "teams_url": None, "status": "Published"},
    {"title": "API Contract Template", "description": "Standard template for API contract documentation", "tags": ["template", "api-contract", "documentation", "standard"], "type": "Doc", "category": "Process", "classification": "Internal", "kind": "Template", "size": "0.9 MB", "uploaded_by": "Charlie", "uploaded_at": "2026-06-22", "downloads": 112, "teams_url": None, "status": "Active"},
    {"title": "GraphQL API Workshop", "description": "Hands-on workshop for building GraphQL APIs", "tags": ["workshop", "graphql", "api", "hands-on"], "type": "Video", "category": "Training", "classification": "Internal", "kind": "Workshop", "size": "210 MB", "uploaded_by": "Diana", "uploaded_at": "2026-06-21", "downloads": 234, "teams_url": "https://teams.microsoft.com/l/file/18", "status": "Published"},
    {"title": "API Marketplace Onboarding Guide", "description": "Step-by-step guide for onboarding partners to the API Marketplace platform", "tags": ["api", "marketplace", "onboarding", "partners"], "type": "PDF", "category": "Integration", "classification": "Internal", "kind": "Accelerator", "size": "3.2 MB", "uploaded_by": "Alice", "uploaded_at": "2026-07-10", "downloads": 189, "teams_url": "https://teams.microsoft.com/l/file/19", "status": "Published"},
    {"title": "API Marketplace Connector Catalog", "description": "Complete catalog of connectors available on the API Marketplace", "tags": ["api", "marketplace", "connectors", "catalog"], "type": "Doc", "category": "Integration", "classification": "External", "kind": "Repository", "size": "1.8 MB", "uploaded_by": "Bob", "uploaded_at": "2026-07-09", "downloads": 312, "teams_url": "https://teams.microsoft.com/l/file/20", "status": "Published"},
    {"title": "API Marketplace Analytics Dashboard", "description": "Analytics and usage metrics for the API Marketplace", "tags": ["api", "marketplace", "analytics", "dashboard"], "type": "Link", "category": "Integration", "classification": "Internal", "kind": "Accelerator", "size": "\u2014", "uploaded_by": "Charlie", "uploaded_at": "2026-07-08", "downloads": 156, "teams_url": "https://teams.microsoft.com/l/file/21", "status": "Published"},
    {"title": "Layer7 API Gateway Configuration Guide", "description": "Comprehensive guide for configuring Layer7 API Gateway for enterprise deployments", "tags": ["layer7", "api-gateway", "configuration", "enterprise"], "type": "Doc", "category": "Cloud", "classification": "Internal", "kind": "Accelerator", "size": "4.5 MB", "uploaded_by": "Diana", "uploaded_at": "2026-07-07", "downloads": 203, "teams_url": "https://teams.microsoft.com/l/file/22", "status": "Published"},
    {"title": "Layer7 Security Policy Templates", "description": "Pre-built security policy templates for Layer7 API Gateway", "tags": ["layer7", "security", "policies", "templates"], "type": "PDF", "category": "Cloud", "classification": "Internal", "kind": "Template", "size": "2.1 MB", "uploaded_by": "Eve", "uploaded_at": "2026-07-06", "downloads": 178, "teams_url": "https://teams.microsoft.com/l/file/23", "status": "Published"},
    {"title": "Layer7 Developer Portal Documentation", "description": "Documentation for setting up and customizing the Layer7 Developer Portal", "tags": ["layer7", "developer-portal", "documentation", "api"], "type": "Doc", "category": "Cloud", "classification": "External", "kind": "Repository", "size": "3.7 MB", "uploaded_by": "Frank", "uploaded_at": "2026-07-05", "downloads": 145, "teams_url": "https://teams.microsoft.com/l/file/24", "status": "Published"},
    {"title": "AI-Powered Fraud Detection PoC", "description": "Proof of concept for AI-based fraud detection in financial transactions", "tags": ["ai", "poc", "fraud-detection", "finance", "machine-learning"], "type": "Doc", "category": "Finance", "classification": "Internal", "kind": "PoC", "size": "5.6 MB", "uploaded_by": "Grace", "uploaded_at": "2026-07-04", "downloads": 98, "teams_url": "https://teams.microsoft.com/l/file/25", "status": "Review"},
    {"title": "AI Chatbot for Customer Support PoC", "description": "Proof of concept for an AI-driven chatbot handling customer support queries", "tags": ["ai", "poc", "chatbot", "customer-support", "nlp"], "type": "Video", "category": "CRM", "classification": "Internal", "kind": "PoC", "size": "89 MB", "uploaded_by": "Alice", "uploaded_at": "2026-07-03", "downloads": 134, "teams_url": "https://teams.microsoft.com/l/file/26", "status": "Active"},
    {"title": "AI Document Classification PoC", "description": "Proof of concept for automated document classification using machine learning", "tags": ["ai", "poc", "document-classification", "machine-learning", "automation"], "type": "Doc", "category": "Process", "classification": "Internal", "kind": "PoC", "size": "2.9 MB", "uploaded_by": "Bob", "uploaded_at": "2026-07-02", "downloads": 87, "teams_url": "https://teams.microsoft.com/l/file/27", "status": "Review"},
    {"title": "Banking Core Integration Deliverable", "description": "Complete client deliverable for banking core system integration project", "tags": ["banking", "core", "integration", "client", "deliverable"], "type": "PDF", "category": "Finance", "classification": "External", "kind": "Client Deliverable", "size": "8.4 MB", "uploaded_by": "Charlie", "uploaded_at": "2026-07-01", "downloads": 67, "teams_url": "https://teams.microsoft.com/l/file/28", "status": "Active"},
    {"title": "Banking Payment Gateway Deliverable", "description": "Client deliverable for payment gateway integration in banking applications", "tags": ["banking", "payment", "gateway", "client", "deliverable"], "type": "Doc", "category": "Finance", "classification": "External", "kind": "Client Deliverable", "size": "6.1 MB", "uploaded_by": "Diana", "uploaded_at": "2026-06-30", "downloads": 54, "teams_url": "https://teams.microsoft.com/l/file/29", "status": "Published"},
]


async def seed_database():
    async with async_session() as session:
        result = await session.execute(select(Asset).limit(1))
        existing = result.scalar_one_or_none()
        if existing is not None:
            return
        for item in ASSETS_SEED:
            asset = Asset(
                title=item["title"],
                description=item["description"],
                tags=json.dumps(item["tags"]),
                type=item["type"],
                category=item["category"],
                classification=item["classification"],
                kind=item["kind"],
                size=item["size"],
                uploaded_by=item["uploaded_by"],
                uploaded_at=item["uploaded_at"],
                downloads=item["downloads"],
                teams_url=item.get("teams_url"),
                status=item.get("status", "Published"),
            )
            session.add(asset)
        await session.commit()
